find_library(YAJL_LIBRARY yajl)
find_path(YAJL_INCLUDE_DIR yajl/yajl_parse.h)
set(YAJL_LIBRARIES ${YAJL_LIBRARY})
set(YAJL_INCLUDE_DIRS ${YAJL_INCLUDE_DIR})
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Yajl DEFAULT_MSG YAJL_LIBRARY YAJL_INCLUDE_DIR)
